//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForwardAirApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.shipmentbooking.forwardair.com/", ConfigurationName="ServiceReference1.FastQuoteService")]
    public interface FastQuoteService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ForwardAirApp.ServiceReference1.getQuoteResponse getQuote(ForwardAirApp.ServiceReference1.getQuote request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult BegingetQuote(ForwardAirApp.ServiceReference1.getQuote request, System.AsyncCallback callback, object asyncState);
        
        ForwardAirApp.ServiceReference1.getQuoteResponse EndgetQuote(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.shipmentbooking.forwardair.com/")]
    public partial class faQuoteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string billToCustomerNumberField;
        
        private string shipperCustomerNumberField;
        
        private string originAirportCodeField;
        
        private string originZipCodeField;
        
        private string destinationAirportCodeField;
        
        private string destinationZipCodeField;
        
        private decimal volumeField;
        
        private bool volumeFieldSpecified;
        
        private VolumetUnitType volumeTypeField;
        
        private bool volumeTypeFieldSpecified;
        
        private Dimension[] dimensionsField;
        
        private FreightDetail[] freightDetailsField;
        
        private YNType hazmatField;
        
        private YNType inBondShipmentField;
        
        private decimal declaredValueField;
        
        private System.DateTime quoteDateField;
        
        private decimal quoteTotalField;
        
        private decimal totalWeightField;
        
        private string transitDaysTotalField;
        
        private ChargeLineItem[] chargeLineItemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=0)]
        public string BillToCustomerNumber {
            get {
                return this.billToCustomerNumberField;
            }
            set {
                this.billToCustomerNumberField = value;
                this.RaisePropertyChanged("BillToCustomerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string ShipperCustomerNumber {
            get {
                return this.shipperCustomerNumberField;
            }
            set {
                this.shipperCustomerNumberField = value;
                this.RaisePropertyChanged("ShipperCustomerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string OriginAirportCode {
            get {
                return this.originAirportCodeField;
            }
            set {
                this.originAirportCodeField = value;
                this.RaisePropertyChanged("OriginAirportCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string OriginZipCode {
            get {
                return this.originZipCodeField;
            }
            set {
                this.originZipCodeField = value;
                this.RaisePropertyChanged("OriginZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DestinationAirportCode {
            get {
                return this.destinationAirportCodeField;
            }
            set {
                this.destinationAirportCodeField = value;
                this.RaisePropertyChanged("DestinationAirportCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string DestinationZipCode {
            get {
                return this.destinationZipCodeField;
            }
            set {
                this.destinationZipCodeField = value;
                this.RaisePropertyChanged("DestinationZipCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
                this.RaisePropertyChanged("Volume");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VolumeSpecified {
            get {
                return this.volumeFieldSpecified;
            }
            set {
                this.volumeFieldSpecified = value;
                this.RaisePropertyChanged("VolumeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public VolumetUnitType VolumeType {
            get {
                return this.volumeTypeField;
            }
            set {
                this.volumeTypeField = value;
                this.RaisePropertyChanged("VolumeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VolumeTypeSpecified {
            get {
                return this.volumeTypeFieldSpecified;
            }
            set {
                this.volumeTypeFieldSpecified = value;
                this.RaisePropertyChanged("VolumeTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Dimension[] Dimensions {
            get {
                return this.dimensionsField;
            }
            set {
                this.dimensionsField = value;
                this.RaisePropertyChanged("Dimensions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FreightDetail[] FreightDetails {
            get {
                return this.freightDetailsField;
            }
            set {
                this.freightDetailsField = value;
                this.RaisePropertyChanged("FreightDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public YNType Hazmat {
            get {
                return this.hazmatField;
            }
            set {
                this.hazmatField = value;
                this.RaisePropertyChanged("Hazmat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public YNType InBondShipment {
            get {
                return this.inBondShipmentField;
            }
            set {
                this.inBondShipmentField = value;
                this.RaisePropertyChanged("InBondShipment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public decimal DeclaredValue {
            get {
                return this.declaredValueField;
            }
            set {
                this.declaredValueField = value;
                this.RaisePropertyChanged("DeclaredValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=13)]
        public System.DateTime QuoteDate {
            get {
                return this.quoteDateField;
            }
            set {
                this.quoteDateField = value;
                this.RaisePropertyChanged("QuoteDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public decimal QuoteTotal {
            get {
                return this.quoteTotalField;
            }
            set {
                this.quoteTotalField = value;
                this.RaisePropertyChanged("QuoteTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public decimal TotalWeight {
            get {
                return this.totalWeightField;
            }
            set {
                this.totalWeightField = value;
                this.RaisePropertyChanged("TotalWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger", Order=16)]
        public string TransitDaysTotal {
            get {
                return this.transitDaysTotalField;
            }
            set {
                this.transitDaysTotalField = value;
                this.RaisePropertyChanged("TransitDaysTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ChargeLineItem[] ChargeLineItems {
            get {
                return this.chargeLineItemsField;
            }
            set {
                this.chargeLineItemsField = value;
                this.RaisePropertyChanged("ChargeLineItems");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.shipmentbooking.forwardair.com/")]
    public enum VolumetUnitType {
        
        /// <remarks/>
        CI,
        
        /// <remarks/>
        CC,
        
        /// <remarks/>
        CF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.shipmentbooking.forwardair.com/")]
    public partial class Dimension : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string piecesField;
        
        private string lengthField;
        
        private string widthField;
        
        private string heightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger", Order=0)]
        public string Pieces {
            get {
                return this.piecesField;
            }
            set {
                this.piecesField = value;
                this.RaisePropertyChanged("Pieces");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger", Order=1)]
        public string Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("Length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger", Order=2)]
        public string Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("Width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="positiveInteger", Order=3)]
        public string Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("Height");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.shipmentbooking.forwardair.com/")]
    public partial class ChargeLineItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        private string zoneField;
        
        private string serviceLevelField;
        
        private decimal amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Zone {
            get {
                return this.zoneField;
            }
            set {
                this.zoneField = value;
                this.RaisePropertyChanged("Zone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ServiceLevel {
            get {
                return this.serviceLevelField;
            }
            set {
                this.serviceLevelField = value;
                this.RaisePropertyChanged("ServiceLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.shipmentbooking.forwardair.com/")]
    public partial class FreightDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal freightClassField;
        
        private string descriptionField;
        
        private string piecesField;
        
        private decimal weightField;
        
        private bool weightFieldSpecified;
        
        private WeightUnitType weightTypeField;
        
        private YNType weightAdjustedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal FreightClass {
            get {
                return this.freightClassField;
            }
            set {
                this.freightClassField = value;
                this.RaisePropertyChanged("FreightClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string Pieces {
            get {
                return this.piecesField;
            }
            set {
                this.piecesField = value;
                this.RaisePropertyChanged("Pieces");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("Weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightSpecified {
            get {
                return this.weightFieldSpecified;
            }
            set {
                this.weightFieldSpecified = value;
                this.RaisePropertyChanged("WeightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public WeightUnitType WeightType {
            get {
                return this.weightTypeField;
            }
            set {
                this.weightTypeField = value;
                this.RaisePropertyChanged("WeightType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public YNType WeightAdjusted {
            get {
                return this.weightAdjustedField;
            }
            set {
                this.weightAdjustedField = value;
                this.RaisePropertyChanged("WeightAdjusted");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.shipmentbooking.forwardair.com/")]
    public enum WeightUnitType {
        
        /// <remarks/>
        L,
        
        /// <remarks/>
        K,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservices.shipmentbooking.forwardair.com/")]
    public enum YNType {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQuote", WrapperNamespace="http://webservices.shipmentbooking.forwardair.com/", IsWrapped=true)]
    public partial class getQuote {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.shipmentbooking.forwardair.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.shipmentbooking.forwardair.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.shipmentbooking.forwardair.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string customerId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.shipmentbooking.forwardair.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string quoteRequest;
        
        public getQuote() {
        }
        
        public getQuote(string user, string password, string customerId, string quoteRequest) {
            this.user = user;
            this.password = password;
            this.customerId = customerId;
            this.quoteRequest = quoteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getQuoteResponse", WrapperNamespace="http://webservices.shipmentbooking.forwardair.com/", IsWrapped=true)]
    public partial class getQuoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.shipmentbooking.forwardair.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ForwardAirApp.ServiceReference1.faQuoteResponse @return;
        
        public getQuoteResponse() {
        }
        
        public getQuoteResponse(ForwardAirApp.ServiceReference1.faQuoteResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FastQuoteServiceChannel : ForwardAirApp.ServiceReference1.FastQuoteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getQuoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getQuoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ForwardAirApp.ServiceReference1.faQuoteResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ForwardAirApp.ServiceReference1.faQuoteResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FastQuoteServiceClient : System.ServiceModel.ClientBase<ForwardAirApp.ServiceReference1.FastQuoteService>, ForwardAirApp.ServiceReference1.FastQuoteService {
        
        private BeginOperationDelegate onBegingetQuoteDelegate;
        
        private EndOperationDelegate onEndgetQuoteDelegate;
        
        private System.Threading.SendOrPostCallback ongetQuoteCompletedDelegate;
        
        public FastQuoteServiceClient() {
        }
        
        public FastQuoteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FastQuoteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FastQuoteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FastQuoteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<getQuoteCompletedEventArgs> getQuoteCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ForwardAirApp.ServiceReference1.getQuoteResponse ForwardAirApp.ServiceReference1.FastQuoteService.getQuote(ForwardAirApp.ServiceReference1.getQuote request) {
            return base.Channel.getQuote(request);
        }
        
        public ForwardAirApp.ServiceReference1.faQuoteResponse getQuote(string user, string password, string customerId, string quoteRequest) {
            ForwardAirApp.ServiceReference1.getQuote inValue = new ForwardAirApp.ServiceReference1.getQuote();
            inValue.user = user;
            inValue.password = password;
            inValue.customerId = customerId;
            inValue.quoteRequest = quoteRequest;
            ForwardAirApp.ServiceReference1.getQuoteResponse retVal = ((ForwardAirApp.ServiceReference1.FastQuoteService)(this)).getQuote(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ForwardAirApp.ServiceReference1.FastQuoteService.BegingetQuote(ForwardAirApp.ServiceReference1.getQuote request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetQuote(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BegingetQuote(string user, string password, string customerId, string quoteRequest, System.AsyncCallback callback, object asyncState) {
            ForwardAirApp.ServiceReference1.getQuote inValue = new ForwardAirApp.ServiceReference1.getQuote();
            inValue.user = user;
            inValue.password = password;
            inValue.customerId = customerId;
            inValue.quoteRequest = quoteRequest;
            return ((ForwardAirApp.ServiceReference1.FastQuoteService)(this)).BegingetQuote(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ForwardAirApp.ServiceReference1.getQuoteResponse ForwardAirApp.ServiceReference1.FastQuoteService.EndgetQuote(System.IAsyncResult result) {
            return base.Channel.EndgetQuote(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public ForwardAirApp.ServiceReference1.faQuoteResponse EndgetQuote(System.IAsyncResult result) {
            ForwardAirApp.ServiceReference1.getQuoteResponse retVal = ((ForwardAirApp.ServiceReference1.FastQuoteService)(this)).EndgetQuote(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBegingetQuote(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string user = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            string customerId = ((string)(inValues[2]));
            string quoteRequest = ((string)(inValues[3]));
            return this.BegingetQuote(user, password, customerId, quoteRequest, callback, asyncState);
        }
        
        private object[] OnEndgetQuote(System.IAsyncResult result) {
            ForwardAirApp.ServiceReference1.faQuoteResponse retVal = this.EndgetQuote(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetQuoteCompleted(object state) {
            if ((this.getQuoteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getQuoteCompleted(this, new getQuoteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getQuoteAsync(string user, string password, string customerId, string quoteRequest) {
            this.getQuoteAsync(user, password, customerId, quoteRequest, null);
        }
        
        public void getQuoteAsync(string user, string password, string customerId, string quoteRequest, object userState) {
            if ((this.onBegingetQuoteDelegate == null)) {
                this.onBegingetQuoteDelegate = new BeginOperationDelegate(this.OnBegingetQuote);
            }
            if ((this.onEndgetQuoteDelegate == null)) {
                this.onEndgetQuoteDelegate = new EndOperationDelegate(this.OnEndgetQuote);
            }
            if ((this.ongetQuoteCompletedDelegate == null)) {
                this.ongetQuoteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetQuoteCompleted);
            }
            base.InvokeAsync(this.onBegingetQuoteDelegate, new object[] {
                        user,
                        password,
                        customerId,
                        quoteRequest}, this.onEndgetQuoteDelegate, this.ongetQuoteCompletedDelegate, userState);
        }
    }
}
