//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class FAQuoteRequest {
    
    private string billToCustomerNumberField;
    
    private string shipperCustomerNumberField;
    
    private Origin originField;
    
    private Destination destinationField;
    
    private decimal volumeField;
    
    private bool volumeFieldSpecified;
    
    private VolumeUnitType volumeTypeField;
    
    private bool volumeTypeFieldSpecified;
    
    private Dimension[] dimensionsField;
    
    private FreightDetail[] freightDetailsField;
    
    private YNType hazmatField;
    
    private YNType inBondShipmentField;
    
    private YNType guaranteedServiceField;
    
    private bool guaranteedServiceFieldSpecified;
    
    private decimal declaredValueField;
    
    private System.DateTime shippingDateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string BillToCustomerNumber {
        get {
            return this.billToCustomerNumberField;
        }
        set {
            this.billToCustomerNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string ShipperCustomerNumber {
        get {
            return this.shipperCustomerNumberField;
        }
        set {
            this.shipperCustomerNumberField = value;
        }
    }
    
    /// <remarks/>
    public Origin Origin {
        get {
            return this.originField;
        }
        set {
            this.originField = value;
        }
    }
    
    /// <remarks/>
    public Destination Destination {
        get {
            return this.destinationField;
        }
        set {
            this.destinationField = value;
        }
    }
    
    /// <remarks/>
    public decimal Volume {
        get {
            return this.volumeField;
        }
        set {
            this.volumeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VolumeSpecified {
        get {
            return this.volumeFieldSpecified;
        }
        set {
            this.volumeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public VolumeUnitType VolumeType {
        get {
            return this.volumeTypeField;
        }
        set {
            this.volumeTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VolumeTypeSpecified {
        get {
            return this.volumeTypeFieldSpecified;
        }
        set {
            this.volumeTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Dimension[] Dimensions {
        get {
            return this.dimensionsField;
        }
        set {
            this.dimensionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public FreightDetail[] FreightDetails {
        get {
            return this.freightDetailsField;
        }
        set {
            this.freightDetailsField = value;
        }
    }
    
    /// <remarks/>
    public YNType Hazmat {
        get {
            return this.hazmatField;
        }
        set {
            this.hazmatField = value;
        }
    }
    
    /// <remarks/>
    public YNType InBondShipment {
        get {
            return this.inBondShipmentField;
        }
        set {
            this.inBondShipmentField = value;
        }
    }
    
    /// <remarks/>
    public YNType GuaranteedService {
        get {
            return this.guaranteedServiceField;
        }
        set {
            this.guaranteedServiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GuaranteedServiceSpecified {
        get {
            return this.guaranteedServiceFieldSpecified;
        }
        set {
            this.guaranteedServiceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal DeclaredValue {
        get {
            return this.declaredValueField;
        }
        set {
            this.declaredValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ShippingDate {
        get {
            return this.shippingDateField;
        }
        set {
            this.shippingDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Origin {
    
    private string originAirportCodeField;
    
    private string originZipCodeField;
    
    private Pickup pickupField;
    
    /// <remarks/>
    public string OriginAirportCode {
        get {
            return this.originAirportCodeField;
        }
        set {
            this.originAirportCodeField = value;
        }
    }
    
    /// <remarks/>
    public string OriginZipCode {
        get {
            return this.originZipCodeField;
        }
        set {
            this.originZipCodeField = value;
        }
    }
    
    /// <remarks/>
    public Pickup Pickup {
        get {
            return this.pickupField;
        }
        set {
            this.pickupField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Pickup {
    
    private YNType airportPickupField;
    
    private PickupAccessorialType[] pickupAccessorialsField;
    
    /// <remarks/>
    public YNType AirportPickup {
        get {
            return this.airportPickupField;
        }
        set {
            this.airportPickupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("PickupAccessorial", IsNullable=false)]
    public PickupAccessorialType[] PickupAccessorials {
        get {
            return this.pickupAccessorialsField;
        }
        set {
            this.pickupAccessorialsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]


/// <remarks/>

public enum PickupAccessorialType {
    
    /// <remarks/>
    AFP,
    
    /// <remarks/>
    ALP,
    
    /// <remarks/>
    APP,
    
    /// <remarks/>
    CCF,
    
    /// <remarks/>
    CCP,
    
    /// <remarks/>
    CPX,
    
    /// <remarks/>
    HOT,
    
    /// <remarks/>
    HPC,
    
    /// <remarks/>
    IPU,
    
    /// <remarks/>
    LGP,
    
    /// <remarks/>
    MBP,
    
    /// <remarks/>
    MOP,
    
    /// <remarks/>
    MPC,
    
    /// <remarks/>
    PJP,
    
    /// <remarks/>
    RPU,
    
    /// <remarks/>
    THP,
    
    /// <remarks/>
    UNC,
    
    /// <remarks/>
    WEP,
    
    /// <remarks/>
    XMP,
    
    /// <remarks/>
    XPU,
}

/// <remarks/>





/// <remarks/>


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Delivery {
    
    private YNType airportDeliveryField;
    
    private DeliveryAccessorialType[] deliveryAccessorialsField;
    
    /// <remarks/>
    public YNType AirportDelivery {
        get {
            return this.airportDeliveryField;
        }
        set {
            this.airportDeliveryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("DeliveryAccessorial", IsNullable=false)]
    public DeliveryAccessorialType[] DeliveryAccessorials {
        get {
            return this.deliveryAccessorialsField;
        }
        set {
            this.deliveryAccessorialsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum DeliveryAccessorialType {
    
    /// <remarks/>
    ADE,
    
    /// <remarks/>
    AFD,
    
    /// <remarks/>
    ALD,
    
    /// <remarks/>
    CCD,
    
    /// <remarks/>
    CPD,
    
    /// <remarks/>
    DR1,
    
    /// <remarks/>
    DR2,
    
    /// <remarks/>
    EMD,
    
    /// <remarks/>
    HDC,
    
    /// <remarks/>
    HOD,
    
    /// <remarks/>
    IDE,
    
    /// <remarks/>
    LGD,
    
    /// <remarks/>
    MBD,
    
    /// <remarks/>
    MDC,
    
    /// <remarks/>
    MOD,
    
    /// <remarks/>
    PJD,
    
    /// <remarks/>
    RDE,
    
    /// <remarks/>
    RDS,
    
    /// <remarks/>
    THD,
    
    /// <remarks/>
    UND,
    
    /// <remarks/>
    UNP,
    
    /// <remarks/>
    WED,
    
    /// <remarks/>
    XPD,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Destination {
    
    private string destinationAirportCodeField;
    
    private string destinationZipCodeField;
    
    private Delivery deliveryField;
    
    /// <remarks/>
    public string DestinationAirportCode {
        get {
            return this.destinationAirportCodeField;
        }
        set {
            this.destinationAirportCodeField = value;
        }
    }
    
    /// <remarks/>
    public string DestinationZipCode {
        get {
            return this.destinationZipCodeField;
        }
        set {
            this.destinationZipCodeField = value;
        }
    }
    
    /// <remarks/>
    public Delivery Delivery {
        get {
            return this.deliveryField;
        }
        set {
            this.deliveryField = value;
        }
    }
}


