//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class FAQuoteResponse {
    
    private string quoteNumberField;
    
    private string[] remarksField;
    
    private string billToCustomerNumberField;
    
    private string shipperCustomerNumberField;
    
    private string originAirportCodeField;
    
    private string originZipCodeField;
    
    private string destinationAirportCodeField;
    
    private string destinationZipCodeField;
    
    private decimal volumeField;
    
    private bool volumeFieldSpecified;
    
    private VolumeUnitType volumeTypeField;
    
    private bool volumeTypeFieldSpecified;
    
    private Dimension[] dimensionsField;
    
    private FreightDetail[] freightDetailsField;
    
    private YNType hazmatField;
    
    private YNType inBondShipmentField;
    
    private YNType guaranteedServiceField;
    
    private bool guaranteedServiceFieldSpecified;
    
    private decimal declaredValueField;
    
    private System.DateTime quoteDateField;
    
    private decimal quoteTotalField;
    
    private decimal totalWeightField;
    
    private string transitDaysTotalField;
    
    private ChargeLineItem[] chargeLineItemsField;
    
    /// <remarks/>
    public string QuoteNumber {
        get {
            return this.quoteNumberField;
        }
        set {
            this.quoteNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Remark", IsNullable=false)]
    public string[] Remarks {
        get {
            return this.remarksField;
        }
        set {
            this.remarksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string BillToCustomerNumber {
        get {
            return this.billToCustomerNumberField;
        }
        set {
            this.billToCustomerNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string ShipperCustomerNumber {
        get {
            return this.shipperCustomerNumberField;
        }
        set {
            this.shipperCustomerNumberField = value;
        }
    }
    
    /// <remarks/>
    public string OriginAirportCode {
        get {
            return this.originAirportCodeField;
        }
        set {
            this.originAirportCodeField = value;
        }
    }
    
    /// <remarks/>
    public string OriginZipCode {
        get {
            return this.originZipCodeField;
        }
        set {
            this.originZipCodeField = value;
        }
    }
    
    /// <remarks/>
    public string DestinationAirportCode {
        get {
            return this.destinationAirportCodeField;
        }
        set {
            this.destinationAirportCodeField = value;
        }
    }
    
    /// <remarks/>
    public string DestinationZipCode {
        get {
            return this.destinationZipCodeField;
        }
        set {
            this.destinationZipCodeField = value;
        }
    }
    
    /// <remarks/>
    public decimal Volume {
        get {
            return this.volumeField;
        }
        set {
            this.volumeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VolumeSpecified {
        get {
            return this.volumeFieldSpecified;
        }
        set {
            this.volumeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public VolumeUnitType VolumeType {
        get {
            return this.volumeTypeField;
        }
        set {
            this.volumeTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VolumeTypeSpecified {
        get {
            return this.volumeTypeFieldSpecified;
        }
        set {
            this.volumeTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public Dimension[] Dimensions {
        get {
            return this.dimensionsField;
        }
        set {
            this.dimensionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public FreightDetail[] FreightDetails {
        get {
            return this.freightDetailsField;
        }
        set {
            this.freightDetailsField = value;
        }
    }
    
    /// <remarks/>
    public YNType Hazmat {
        get {
            return this.hazmatField;
        }
        set {
            this.hazmatField = value;
        }
    }
    
    /// <remarks/>
    public YNType InBondShipment {
        get {
            return this.inBondShipmentField;
        }
        set {
            this.inBondShipmentField = value;
        }
    }
    
    /// <remarks/>
    public YNType GuaranteedService {
        get {
            return this.guaranteedServiceField;
        }
        set {
            this.guaranteedServiceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GuaranteedServiceSpecified {
        get {
            return this.guaranteedServiceFieldSpecified;
        }
        set {
            this.guaranteedServiceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal DeclaredValue {
        get {
            return this.declaredValueField;
        }
        set {
            this.declaredValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime QuoteDate {
        get {
            return this.quoteDateField;
        }
        set {
            this.quoteDateField = value;
        }
    }
    
    /// <remarks/>
    public decimal QuoteTotal {
        get {
            return this.quoteTotalField;
        }
        set {
            this.quoteTotalField = value;
        }
    }
    
    /// <remarks/>
    public decimal TotalWeight {
        get {
            return this.totalWeightField;
        }
        set {
            this.totalWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string TransitDaysTotal {
        get {
            return this.transitDaysTotalField;
        }
        set {
            this.transitDaysTotalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public ChargeLineItem[] ChargeLineItems {
        get {
            return this.chargeLineItemsField;
        }
        set {
            this.chargeLineItemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum VolumeUnitType {
    
    /// <remarks/>
    CI,
    
    /// <remarks/>
    CC,
    
    /// <remarks/>
    CF,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Dimension {
    
    private string piecesField;
    
    private string lengthField;
    
    private string widthField;
    
    private string heightField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string Pieces {
        get {
            return this.piecesField;
        }
        set {
            this.piecesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string Length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string Height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ChargeLineItem {
    
    private string codeField;
    
    private string descriptionField;
    
    private string zoneField;
    
    private string serviceLevelField;
    
    private decimal amountField;
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Zone {
        get {
            return this.zoneField;
        }
        set {
            this.zoneField = value;
        }
    }
    
    /// <remarks/>
    public string ServiceLevel {
        get {
            return this.serviceLevelField;
        }
        set {
            this.serviceLevelField = value;
        }
    }
    
    /// <remarks/>
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class FreightDetail {
    
    private decimal freightClassField;
    
    private string descriptionField;
    
    private string piecesField;
    
    private decimal weightField;
    
    private WeightUnitType weightTypeField;
    
    private YNType weightAdjustedField;
    
    /// <remarks/>
    public decimal FreightClass {
        get {
            return this.freightClassField;
        }
        set {
            this.freightClassField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string Pieces {
        get {
            return this.piecesField;
        }
        set {
            this.piecesField = value;
        }
    }
    
    /// <remarks/>
    public decimal Weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    public WeightUnitType WeightType {
        get {
            return this.weightTypeField;
        }
        set {
            this.weightTypeField = value;
        }
    }
    
    /// <remarks/>
    public YNType WeightAdjusted {
        get {
            return this.weightAdjustedField;
        }
        set {
            this.weightAdjustedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum WeightUnitType {
    
    /// <remarks/>
    L,
    
    /// <remarks/>
    K,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
public enum YNType {
    
    /// <remarks/>
    Y,
    
    /// <remarks/>
    N,
}
